# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - cyclop
    - prealloc
    - sloglint
    - testifylint
    - wsl_v5
    - tparallel
  settings:
    staticcheck:
      checks:
        [
          "all",
          "-SA9003",
          "-ST1000",
          "-ST1003",
          "-ST1016",
          "-ST1020",
          "-ST1021",
          "-ST1022",
          "-ST1023",
        ]
    cyclop:
      max-complexity: 15
      package-average: 10.0
    errcheck:
      check-type-assertions: true
      check-blank: true
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - cyclop

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
